name:  Scaffold for any python project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Set up python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.12
    - name: Install Dependencies
      run: |
        make install
    - name: Lint with python
      run: |
        make lint
    - name: Format with black
      run: |
        make format
    - name: Test with python
      run: |
       make test
  
